## Importing Panda

In [2]:
import pandas as pd

## Importing CSVs

In [3]:
df0 = pd.read_csv('Drone_RCS_Measurement_Dataset/P4P_HH.csv')
df1 = pd.read_csv('Drone_RCS_Measurement_Dataset/F450_HH.csv')
df2 = pd.read_csv('Drone_RCS_Measurement_Dataset/Heli_HH.csv')
df3 = pd.read_csv('Drone_RCS_Measurement_Dataset/Hexa_HH.csv')
df4 = pd.read_csv('Drone_RCS_Measurement_Dataset/M100_HH.csv')
df5 = pd.read_csv('Drone_RCS_Measurement_Dataset/Y600_HH.csv')
df6 = pd.read_csv('Drone_RCS_Measurement_Dataset/Mavic_HH.csv')
df7 = pd.read_csv('Drone_RCS_Measurement_Dataset/Parrot_HH.csv')
df8 = pd.read_csv('Drone_RCS_Measurement_Dataset/battery_HH.csv')
df9 = pd.read_csv('Drone_RCS_Measurement_Dataset/Walkera_HH.csv')

## Adding Name column

In [4]:
df0['Type'] = '0'
df1['Type'] = '1'
df2['Type'] = '2'
df3['Type'] = '3'
df4['Type'] = '4'
df5['Type'] = '5'
df6['Type'] = '6'
df7['Type'] = '7'
df8['Type'] = '8'
df9['Type'] = '9'

## Merging all datasets

In [12]:
frames = [df0, df1, df2, df3, df4, df5, df6, df7, df8, df9]
#frames = [df0, df1, df2]

result = pd.concat(frames)
result.reset_index(drop=True, inplace=True)
print(result)

         f[GHz]  theta[deg]  phi[deg]  RCS[dB] Type
0            26         -95         0 -13.8250    0
1            26         -94         0 -13.6300    0
2            26         -93         0 -27.9430    0
3            26         -92         0 -11.8610    0
4            26         -91         0 -12.1860    0
...         ...         ...       ...      ...  ...
4655545      40          91       180   1.9699    9
4655546      40          92       180  -5.3061    9
4655547      40          93       180  -5.7171    9
4655548      40          94       180 -27.2100    9
4655549      40          95       180 -15.3950    9

[4655550 rows x 5 columns]


### Exporting CSV 

In [13]:
result.to_csv('merged_df.csv')

### Linear Regression

In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
# , 'theta[deg]', 'phi[deg]'
X = result.drop(columns=['Type'])
#print(X)
y = result['Type']
#print(y)
reg = LinearRegression().fit(X, y)
print(reg.score(X,y))
print(reg.coef_)
print(reg.intercept_)

0.08665105829040542
[-0.00211722  0.007764   -0.00816264  0.00918659]
4.851935865210905


### Ridge

In [38]:
from sklearn import linear_model

reg1 = linear_model.Ridge(alpha=.5)
reg1.fit(X, y)
print(reg1.score(X,y))
print(reg1.coef_)
print(reg1.intercept_)

0.08665105829040576
[-0.00211722  0.007764   -0.00816264  0.00918659]
4.851935864362599


### Lasso - so a priori che va peggio

In [40]:
reg2 = linear_model.Lasso(alpha=.1)
reg2.fit(X, y)
print(reg2.score(X,y))
print(reg2.coef_)
print(reg2.intercept_)

0.08661570762440196
[-0.          0.00772604 -0.00812141  0.0071198 ]
4.751493846379054


### LARS Lasso

In [44]:
reg3 = linear_model.LassoLars(alpha=.1, normalize=False)
reg3.fit(X, y)
print(reg3.score(X,y))
print(reg3.coef_)
print(reg3.intercept_)

0.08661570714097155
[ 0.          0.00772603 -0.00812142  0.00711979]
4.751494043872992


### LARS

In [46]:
reg4 = linear_model.Lars(n_nonzero_coefs=1, normalize=False)
reg4.fit(X, y)
print(reg4.score(X,y))
print(reg4.coef_)
print(reg4.intercept_)

1.7763568394002505e-14
[ 0.00000000e+00  0.00000000e+00 -1.30101449e-15  0.00000000e+00]
4.223942391339461


### Orthogonal MAtching Pursuit

### Bayesian Regression

In [47]:
reg5 = linear_model.BayesianRidge()
reg5.fit(X, y)
print(reg5.score(X,y))
print(reg5.coef_)
print(reg5.intercept_)

0.08665105807552353
[-0.00211277  0.00776391 -0.00816254  0.00918129]
4.851710767688039


### Generalized Linear Regression

In [52]:
# power = 0: normal, 1:poisson, 2:gamma, 3: inverse gaussian
reg6 = linear_model.TweedieRegressor(power=0, alpha=0.5, link='log')
reg6.fit(X, y)
print(reg6.score(X,y))
print(reg6.coef_)
print(reg6.intercept_)

0.0936699593369199
[-0.00042066  0.00188587 -0.00194106  0.00172367]
1.5587573869463482


### Polynomial regression: extending linear models with basis functions¶
[Scikit Learn Docs](https://scikit-learn.org/stable/modules/linear_model.html#orthogonal-matching-pursuit-omp)

In [12]:
# from sklearn.linear_model import Perceptron
# from sklearn.preprocessing import PolynomialFeatures
# import numpy as np

X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)
clf = Perceptron(fit_intercept=True, max_iter=50, tol=None, shuffle=False).fit(X,y)

clf.score(X,y)

0.1593760135751952

# SVM Classification

In [8]:
from sklearn import svm

In [ ]:
clf = svm.SVC()
clf.fit(X,y)
print(clf.score(X,y))

# SGDClassifier

## Stochastic Gradient Descend

In [31]:
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf1 = make_pipeline(StandardScaler(), SGDClassifier(n_jobs = -1, max_iter=11000, tol=1e-3, learning_rate='adaptive', eta0=1))
clf1.fit(X,y)

clf1.score(X,y)


0.1847811751565336